from selenium import webdriver
from selenium.webdriver.firefox.options import Options
from selenium.webdriver.firefox.service import Service
import time

# Set up Firefox options
options = Options()
options.add_argument("--headless")
options.binary_location = "/usr/bin/firefox"  # Replace with actual path if different

# Specify path to geckodriver using Service
service = Service(
    executable_path="/usr/local/bin/geckodriver",  # Path to geckodriver
    log_path="./geckodriver.log"  # Path to log file
)
# Initialize the Firefox driver with the service
driver = webdriver.Firefox(service=service, options=options)

# Go to YouTube login page
driver.get("https://accounts.google.com/signin")

# Automate login - fill in your YouTube/Google email and password
driver.find_element("id", "identifierId").send_keys("gandalfmanny61@gmail.com")
driver.find_element("id", "identifierNext").click()
time.sleep(5)  # Wait for the password field to load

driver.find_element("name", "Passwd").send_keys("Fdfody07")
driver.find_element("id", "passwordNext").click()
time.sleep(5)  # Wait for login to complete

driver.get("https://www.youtube.com")
time.sleep(5)  # Ensure page loads fully


# Save cookies in Netscape format for yt-dlp compatibility
cookies = driver.get_cookies()
with open("cookies.txt", "w") as file:
    # Write the header for Netscape format
    file.write("# Netscape HTTP Cookie File\n")
    file.write("# This file was generated by selenium script\n")
    file.write("# Fields: domain, flag, path, secure, expiration, name, value\n")

    # Write cookies in the correct format
    for cookie in cookies:
        # Convert expiry time to a string (if available)
        expiry = cookie.get('expiry', '')
        if expiry:
            expiry = str(int(expiry))  # Convert expiry to a string

        # Write each cookie in the required format (tab-separated)
        file.write(
            f"{cookie['domain']}\tTRUE\t{cookie['path']}\t{str(cookie['secure']).upper()}\t{expiry}\t{cookie['name']}\t{cookie['value']}\n")

print("Cookies saved to cookies.txt")

driver.quit()
